apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-application-claim
  namespace: project
spec:
  storageClassName: todo-application-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
