apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-application
  template:
    metadata:
      labels:
        app: todo-application
    spec:
      volumes:
        - name: shared-todo-application
          persistentVolumeClaim:
            claimName: todo-application-claim
      containers:
        - name: todo-application
          image: pavezzo/todo-application:c775fd44195bc6eeb3722ae710c5f2bce5f67f8b
          volumeMounts:
            - name: shared-todo-application
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
