apiVersion: v1
kind: Service
metadata:
  name: todo-application-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: todo-application
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
