apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          # image: pavezzo/todo-backend:53b4f69bc244e2b0fe947196aa09e03a5d1fd66a
          image: PROJECT/IMAGE-BACKEND
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
          env:
            - name: PORT
              value: "3000"
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-backend-db-password
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_USER
              value: "postgres"
            - name: DB_NAME
              value: "postgres"

