apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: pavezzo/todo-backend:0882909c461f023f8aecc5d4251d1e56a5af1353
          env:
            - name: PORT
              value: "3000"
