apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: pavezzo/ping-pong:146aeab4a7684bd8c941c570811817f1efc89af6
          env:
            - name: PORT
              value: "3002"
