apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      # volumes:
      #   - name: shared-pong
      #     persistentVolumeClaim:
      #       claimName: log-pong-claim
      containers:
        - name: ping-pong
          image: pavezzo/ping-pong:ef0700e2a6b330e88d1e7357e489f3fc0ce4cffa
          # volumeMounts:
          #   - name: shared-pong
          #     mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3002"
