apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log-output
          persistentVolumeClaim:
            claimName: log-pong-claim
        - name: information-file
          configMap:
            name: log-output-configmap
      containers:
        - name: log-output-writer
          image: pavezzo/log-output-writer:d23049304b9bf6f8abd2d8049b30bb84504a1be0
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: pavezzo/log-output-reader:6db32de1f32d3749d4d5afa6f23f9efebc09f9ee
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
            - name: information-file
              mountPath: /usr/src/app/information
              readOnly: true
          env:
            - name: PORT
              value: "3001"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
