apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log-output
          persistentVolumeClaim:
            claimName: log-pong-claim
      containers:
        - name: log-output-writer
          image: pavezzo/log-output-writer:d23049304b9bf6f8abd2d8049b30bb84504a1be0
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: pavezzo/log-output-reader:7502b5d5878930eefd023c2f2d5bf1414b405932
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3001"
