apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log-output
          persistentVolumeClaim:
            claimName: log-output-claim
        - name: information-file
          configMap:
            name: log-output-configmap
      containers:
        - name: log-output-writer
          image: pavezzo/log-output-writer:d23049304b9bf6f8abd2d8049b30bb84504a1be0
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: pavezzo/log-output-reader:9a07d88fa89acfc8ca519a003c7e78cedd3d8da0
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
            - name: information-file
              mountPath: /usr/src/app/information
              readOnly: true
          env:
            - name: PORT
              value: "3001"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-claim
  namespace: exercises
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
